### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Reza9472** [AmasiaNalbandian/static-site-generator#1]
The instructions could be a bit more clear.
For installing packages and also adding the `"bin": {
    "create-html": "bin/create-html"
  },` since the package.json was not included.
  Also the instructions could point out where the text files should be and/or where the HTML files would be created

**Comment by humphd** [comment]
Agreed. I was just coming to file the same.  The README needs to be greatly expanded to include both reference details (e.g., which flags are supported) and also usage info and examples, so users can learn.

**Comment by AmasiaNalbandian** [comment]
The readme was updated in week 3 and therefore I am closing this issue.
