### ISSUE TITLE
Correct license field in package.json

### ISSUE THREAD

**Issue by humphd** [AmasiaNalbandian/static-site-generator#11]
The LICENSE file is using the MIT License, but the `package.json` doesn't list this, see https://github.com/AmasiaNalbandian/static-site-generator/blob/main/package.json#L20

**Comment by AmasiaNalbandian** [comment]
closing as per this [commit](https://github.com/AmasiaNalbandian/static-site-generator/commit/2a95ec155678210dc8a83e4fd0136f0bb2c73c8f) addresses the issue.
