### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by humphd** [AmasiaNalbandian/static-site-generator#13]
When dealing with errors, remember that users can't understand when you give them a raw Error object: https://github.com/AmasiaNalbandian/static-site-generator/blob/main/src/main.js#L100.  Instead, provide a useful error message, and exit the program with an error code:

```js
if(err) {
  console.error('Helpful error message here...');
  process.exit(1);
}
```

**Comment by AmasiaNalbandian** [comment]
Thank you for taking the time to create this issue. I am closing as per this [commit](https://github.com/AmasiaNalbandian/static-site-generator/commit/2a95ec155678210dc8a83e4fd0136f0bb2c73c8f) addresses the issue.
